repos:
  - repo: local
    hooks:
#      - id: poetry-lock
#        name: Check poetry.lock consistency
#        language: system
#        entry: poetry run poe check-lock
#        always_run: true
#        pass_filenames: false
      - id: lint
        name: Run poe lint
        language: system
        entry: poetry run poe lint
        always_run: true
        pass_filenames: false
      - id: pyproject-fmt
        name: Run poe pyproject-fmt
        language: system
        entry: poetry run poe pyproject-fmt
        always_run: true
        pass_filenames: false
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-json
        - id: check-yaml
        - id: check-toml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: forbid-new-submodules
        - id: mixed-line-ending
          args: ["--fix=no"]
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        -   id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--check"]
      - id: poetry-export
        args: ["--with", "dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
#  - repo: https://github.com/tox-dev/pyproject-fmt
#    rev: "0.3.5"
#    hooks:
#      - id: pyproject-fmt
#        args: pyproject.toml
