sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5

cache: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35

install:
  - pip install -r requirements-dev.txt

script:
  - tox -e $TOX_ENV
