name: Tox Tests

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy: [2022-10-24 Christo] This repo uses tox for the matrix
#      matrix:
#        python-version: [ "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      id: setup_python
      with:
        python-version: 3.9
        #cache: poetry
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test with tox
      run: tox